apiVersion: v1
kind: Service
metadata:
  name: healthmed-rabbitmq
  namespace: fiap-healthmed
spec:
  type: NodePort
  selector:
    app: healthmed-rabbitmq
  ports:
  - name: amqp
    port: 5672
    targetPort: 5672
  - name: amqp-ui
    port: 15672
    targetPort: 15672
    nodePort: 32072