version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fiap_healthmed_api
    ports:
      - "7209:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Connection_String=Server=mysql;port=3306;database=HealthMed;uid=root;pwd=202406
      - MassTransit_Servidor=host.docker.internal
      - MassTransit_Usuario=guest
      - MassTransit_Senha=guest
      - MassTransit_Filas_UsuarioFila=usuario-queue
      - MassTransit_Filas_ConsultaFila=consulta-queue
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - default

  mysql:
    image: mysql:8.0.32
    container_name: mysql-fiap-HealthMed
    environment:
      MYSQL_ROOT_PASSWORD: 202406
    ports:
      - "3360:3306"
    volumes:
      - ./src/FIAP_HealthMed.Data/Scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fiap_healthmed-worker
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Connection_String=Server=mysql;port=3306;database=HealthMed;uid=root;pwd=202406
      - MassTransit_Servidor=host.docker.internal
      - MassTransit_Usuario=guest
      - MassTransit_Senha=guest
      - MassTransit_Filas_ContatoFila=usuario-queue
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - default
