version: '3.8'

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
      target: api
    container_name: fiap_healthmed_api
    ports:
      - "7209:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Connection_String=Server=mysql;port=3306;database=HealthMed;uid=root;pwd=202406
      - MassTransit_Servidor=host.docker.internal
      - MassTransit_Usuario=guest
      - MassTransit_Senha=guest
      - MassTransit_Filas_UsuarioFila=usuario-queue
      - MassTransit_Filas_ConsultaFila=consulta-queue
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - default

  mysql:
    image: mysql:8.0.32
    container_name: mysql-fiap-HealthMed
    environment:
      MYSQL_ROOT_PASSWORD: 202406
    ports:
      - "3360:3306"
    volumes:
      - ./src/FIAP_HealthMed.Data/Scripts:/docker-entrypoint-initdb.d
    restart: always
    networks:
      - default
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    depends_on:
      - api
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:9090/
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - default

  cadvisor:
    image: google/cadvisor:latest
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /sys:/sys
      - /var/lib/docker/:/var/lib/docker/
    networks:
      - default

  grafana:
    container_name: grafana
    image: grafana/grafana:11.2.0
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./src/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./src/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./src/grafana/data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
    healthcheck:
      test: wget -q --tries=1 -O- http://localhost:3000/
      interval: 3s
      timeout: 3s
      retries: 10
      start_period: 10s
    networks:
      - default

  rabbitmq:
    image: masstransit/rabbitmq
    container_name: rabbitmq
    restart: always
    ports:
      - "15672:15672"
      - "5672:5672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - default

  worker:
    build:
      context: ./
      dockerfile: Dockerfile
      target: worker
    container_name: fiap_healthmed_worker
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Connection_String=Server=mysql;port=3306;database=HealthMed;uid=root;pwd=202406
      - MassTransit_Servidor=host.docker.internal
      - MassTransit_Usuario=guest
      - MassTransit_Senha=guest
      - MassTransit_Filas_UsuarioFila=usuario-queue
    depends_on:
      mysql:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - default
