apiVersion: v1
kind: Service
metadata:
  name: healthmed-mysql
  namespace: fiap-healthmed
spec:
  type: NodePort
  selector:
    app: healthmed-mysql
  ports:
  - port: 3306
    targetPort: 3306
    nodePort: 32006
    protocol: TCP
    name: mysql
