apiVersion: v1
kind: Secret
metadata:
  name: fiap-healthmed-secret
  namespace: fiap-healthmed
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: cm9vdA==        
  MYSQL_USER: cm9vdA==                 
  MYSQL_PASSWORD: cm9vdA==            
