{
 "title": "FIAP-HealthMed (Prometheus) 2",
 "description": "Metricas usando o  prometheus-net middleware",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": " Status de Resposta",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (code) (rate(http_requests_received_total[5m]) * 300)",
     "legendFormat": "{{code}}"
    }
   ]
  },
  {
   "title": "Latência Percentil 95",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket[5m])) by (le, method, endpoint)) > 0",
     "legendFormat": "{{method}} - {{endpoint}}"
    }
   ]
  },
  {
   "title": "Uso de CPU (%)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "sum(rate(process_cpu_seconds_total[5m])) by (job)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uso de Memória",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "process_private_memory_bytes", "legendFormat": "__auto" }
   ]
  },
  {
   "title": " Latência Conexão MySql 95º percentil",
   "type": "stat",
   "gridPos": { "h": 7, "w": 12, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, rate(mysqlconnector_db_client_connections_use_time_bucket{pool_name=\"Server=host.docker.internal;Port=3306;User ID=root;Database=HealthMed\"}[5m]))",
     "legendFormat": "{{database}}"
    }
   ]
  }
 ]
}