apiVersion: v1
kind: Service
metadata:
  name: healthmed-api-service
  namespace: fiap-healthmed
spec:
  type: NodePort
  selector:
    app: healthmed-api
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 32080